# Generated by Django 4.1.7 on 2023-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_voyage_number_of_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='Number_of_attendees',
            field=models.IntegerField(choices=[('1 person', '1 person'), ('2 person', '2 person'), ('3 person', '3 person'), ('4 person', '4 person'), ('5 person', '5 person'), ('6 person', '6 person'), ('7 person', '7 person'), ('8 person', '8 person'), ('9 person', '9 person'), ('+10 person', '+10 person'), ('+20 person', '+20 person')]),
        ),
    ]
