# Generated by Django 4.1.7 on 2023-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_voyage_number_of_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='Number_of_attendees',
            field=models.IntegerField(choices=[('oneperson', 'oneperson'), ('twoperson', 'twoperson'), ('threeperson', 'threeperson'), ('fourperson', 'fourperson')]),
        ),
    ]
