# Generated by Django 4.1.7 on 2023-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_voyage_number_of_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
    ]
