# Generated by Django 4.1.7 on 2023-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_voyage_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='accept_terms',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=50),
        ),
    ]
