# Generated by Django 4.1.7 on 2023-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_guide_alter_voyage_guide_language_alter_voyage_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.IntegerField(),
        ),
    ]
