# Generated by Django 4.1.7 on 2023-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_guide_identity_pic_alter_guide_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_nbr', models.CharField(max_length=50)),
                ('rent_from', models.DateField()),
                ('rent_to', models.DateField()),
                ('License_nbr', models.CharField(max_length=50)),
                ('Transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=50)),
                ('Fuel', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electricity', 'Electricity')], max_length=50)),
                ('identity_card', models.ImageField(null=True, upload_to='identitypics_cars/%y/%m/%d')),
                ('driving_license', models.ImageField(null=True, upload_to='driving_license/%y/%m/%d')),
                ('car_pic', models.ImageField(null=True, upload_to='cars_pics/%y/%m/%d')),
                ('notes', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='guide',
            name='identity_pic',
            field=models.ImageField(null=True, upload_to='identity_pics/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='sexe',
            field=models.CharField(choices=[('F', 'femme'), ('M', 'homme')], max_length=50),
        ),
    ]
